# apiVersion: v1
# kind: Service
# metadata:
#   name: 
#   labels:
#     env: dev
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#   selector:
#     env: dev


apiVersion: v1
kind: Service
metadata:
  name: react-devops-service
spec:
  selector:
    app: react-devops
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer